# This file is machine-generated - editing it directly is not advised

julia_version = "1.13.0-DEV"
manifest_format = "2.0"
project_hash = "2ba095eea143434854ea510082d0697aa2bcd3f3"

[[deps.Example]]
git-tree-sha1 = "e1f0e1a832ccd8e97d6d0348dec33ee139a5aeaf"
uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
version = "0.5.5"
